version: "3.5"

services:

  portainer:
    image: portainer/portainer:latest
    restart: always
    ports:
      - "127.0.0.1:9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/offgrid/portainer_data:/data
    labels:
      - "traefik.http.routers.portainer.rule=Host(`portainer`)"
      - "traefik.http.routers.portainer.entrypoints=web,websecure"

  netdata:
    image: netdata/netdata
    restart: always
    ports:
      - "127.0.0.1:19999:19999"
    volumes:
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    labels:
      - "traefik.http.routers.netdata.rule=Host(`netdata`)"
      - "traefik.http.routers.netdata.entrypoints=web,websecure"