version: "3"

services:

  mysql:
    image: mysql:latest
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./offgrid/db_data:/var/lib/mysql
      - ./database_init.mysql.sql:/docker-entrypoint-initdb.d/dsatabase_init.mysql.sql:ro
    ports:
      - "127.0.0.1:3306:3306"
    networks:
      - offgrid
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${OFFGRID_DATABASE_ROOT_PASSWORD}
      - MYSQL_USER=offgrid
      - MYSQL_PASSWORD=${OFFGRID_DATABASE_PASSWORD}
      - TZ=Asia/Shanghai

  graphite:
    image: graphiteapp/graphite-statsd
    restart: always
    ports:
      - "127.0.0.1:8100:80"
      - "127.0.0.1:2003-2004:2003-2004"
      - "127.0.0.1:2023-2024:2023-2024"
      - "127.0.0.1:8125:8125/udp"
      - "127.0.0.1:8126:8126"
    networks:
      - offgrid

  hydra:
    depends_on:
      - hydra-migrate
    image: oryd/hydra:latest
    ports:
      - "127.0.0.1:4444:4444" # Public port
      - "127.0.0.1:4445:4445" # Admin port
      - "127.0.0.1:5555:5555" # Port for hydra token user
    networks:
      - offgrid
    restart: unless-stopped
    command:
      serve all --dangerous-force-http
    environment:
      - URLS_SELF_ISSUER=${OFFGRID_HYDRA_HOST}
      - URLS_LOGIN=${OFFGRID_HOST}/hydra/login
      - URLS_CONSENT=${OFFGRID_HOST}/hydra/consent
      - URLS_LOGOUT=${OFFGRID_HOST}/hydra/logout # currently unsupported
      - DSN=mysql://root:${OFFGRID_DATABASE_ROOT_PASSWORD}@tcp(mysql:3306)/hydra?max_conns=20&max_idle_conns=4
      - SECRETS_SYSTEM=${OFFGRID_HYDRA_SECRETS_SYSTEM}
    labels:
      - "traefik.http.middlewares.gzip.compress=true"
      - "traefik.http.routers.hydra.rule=Path(`/service/oauth`)"
      - "traefik.http.routers.hydra.middlewares=gzip"
      - "traefik.http.routers.hydra.entrypoints=http"

  hydra-migrate:
    image: oryd/hydra
    environment:
      - DSN=mysql://root:${OFFGRID_DATABASE_ROOT_PASSWORD}@tcp(mysql:3306)/hydra?max_conns=20&max_idle_conns=4
    networks:
      - offgrid
    command:
      migrate sql -e --yes
    restart: on-failure

  backend:
    build: "."
    #    volumes:
    #      - ./offgrid/backend:/offgrid
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - offgrid
    restart: always
    environment:
      - OFFGRID_HOST=${OFFGRID_HOST}
      - OFFGRID_HYDRA_HOST=${OFFGRID_HYDRA_HOST}
      - OFFGRID_GRAPHITE_HOST=graphite
      - OFFGRID_BACKEND_JDBC_URL=jdbc:mysql://database:3306/offgrid
      - OFFGRID_ALIYUN_DIRECTMAIL_ACCESS_KEY_ID=${OFFGRID_ALIYUN_DIRECTMAIL_ACCESS_KEY_ID}
      - OFFGRID_ALIYUN_DIRECTMAIL_ACCESS_KEY_SECRET=${OFFGRID_ALIYUN_DIRECTMAIL_ACCESS_KEY_SECRET}

networks:
  offgrid:
    name: offgrid